language: node_js
sudo: true
node_js:
  - "4.0"
  - "4.4"
  - "5.0"
  - "stable"
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
  - npm -g install npm@latest-2
  - "gem install --version 0.8.9 faraday"
before_script:
  - sudo apt-get install gcloud
  - gcloud beta emulators datastore start --no-store-on-disk
script: "npm run-script test-coverage"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
