# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coveralls coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: default gcloud uninstall
      run: sudo apt-get remove --purge google-cloud-sdk

    - name: gcloud install
      run: |
        curl https://sdk.cloud.google.com > install.sh
        bash install.sh --disable-prompts

    - name: install & start emulator
      run: |
        source /home/runner/google-cloud-sdk/path.bash.inc
        gcloud components install --quiet cloud-datastore-emulator
        gcloud components install --quiet beta
        gcloud beta emulators datastore start --project nodetsdb-gce-integration-testing --no-store-on-disk --host-port localhost:8081 &

    - run: npm ci
    - run: npm run test-coverage
    - run: ./node_modules/nyc/bin/nyc.js report --reporter=lcov
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.0
      env:
        NODE_COVERALLS_DEBUG: 1
      with:
        github-token: ${{ secrets.github_token }}
