# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coveralls coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # Create environment variable for correct distribution
    - run: export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
    # Add the Cloud SDK distribution URI as a package source
    - run: echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    # Import the Google Cloud Platform public key
    - run: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
    # Update the package list and install the Cloud SDK
    - run: sudo apt-get update && sudo apt-get install google-cloud-sdk
    # Install the emulator
    - run: sudo apt-get install google-cloud-sdk-datastore-emulator
    # Start the datastore emulator
    - run: gcloud beta emulators datastore start --no-store-on-disk --host-port localhost:8081 &
    # Make sure we can find it..
    - run: export DATASTORE_EMULATOR_HOST=localhost:8081
    - run: npm ci
    - run: npm run test-coverage
    - run: ./node_modules/nyc/bin/nyc.js report --reporter=lcov
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.0
      env:
        NODE_COVERALLS_DEBUG: 1
      with:
        github-token: ${{ secrets.github_token }}
