# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DATASTORE_EMULATOR_HOST: localhost:8081

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        sudo apt-get remove --purge google-cloud-sdk
        # gcloud install
        curl https://sdk.cloud.google.com > install.sh
        bash install.sh --disable-prompts
        # gcloud command
        source /home/runner/google-cloud-sdk/path.bash.inc
        # Install the emulator
        gcloud components install cloud-datastore-emulator
        # Start the datastore emulator
        gcloud beta emulators datastore start --no-store-on-disk --host-port localhost:8081 &
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
